from flask import render_template, request, redirect, url_for, flash, jsonify, send_file
import math
import re
from io import BytesIO

import pandas as pd

from db import conectar_db
from . import procedimentos_bp


# =========================================================
# CONEXÃO (POSTGRES)
# =========================================================
def get_conn():
    return conectar_db()


# =========================================================
# HELPERS
# =========================================================
def normalize_text(v):
    return str(v or "").strip()


def only_digits(v):
    return re.sub(r"\D+", "", str(v or ""))


def safe_like(v):
    return f"%{normalize_text(v)}%"


def to_float(v):
    try:
        txt = str(v or "").strip()
        if not txt:
            return 0.0

        txt = txt.replace("R$", "").replace(" ", "")

        if "," in txt and "." in txt:
            txt = txt.replace(".", "").replace(",", ".")
        else:
            txt = txt.replace(",", ".")

        return float(txt)
    except Exception:
        return 0.0


def to_int(v):
    try:
        txt = only_digits(v)
        return int(txt) if txt else 0
    except Exception:
        return 0


def get_col(row, *names):
    """
    Busca uma coluna no DataFrame tolerando nomes alternativos.
    Exemplo: codigo, co_procedimento, Código etc.
    """
    for name in names:
        if name in row:
            return row.get(name)
    return ""


# =========================================================
# SCHEMA (POSTGRES)
# =========================================================
def ensure_schema():
    conn = get_conn()

    try:
        cur = conn.cursor()

        cur.execute("""
            CREATE TABLE IF NOT EXISTS procedimentos (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                codigo TEXT,
                descricao TEXT,
                complexidade TEXT,
                competencia TEXT,

                valor_sh NUMERIC(14, 2) DEFAULT 0,
                valor_sa NUMERIC(14, 2) DEFAULT 0,
                valor_sp NUMERIC(14, 2) DEFAULT 0,
                valor_total NUMERIC(14, 2) DEFAULT 0,

                co_financiamento TEXT,
                no_financiamento TEXT,
                co_rubrica TEXT,
                no_rubrica TEXT,

                qtd_cids INTEGER DEFAULT 0,
                cids_codigos TEXT,
                cids_descricoes TEXT,

                qtd_cbos INTEGER DEFAULT 0,
                cbos_codigos TEXT,
                cbos_descricoes TEXT,

                qtd_servicos INTEGER DEFAULT 0,
                servicos_codigos TEXT,
                servicos_descricoes TEXT,

                classificacoes_codigos TEXT,
                classificacoes_descricoes TEXT,

                criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Colunas novas, caso a tabela já exista antiga
        alter_columns = {
            "codigo": "TEXT",
            "descricao": "TEXT",
            "complexidade": "TEXT",
            "competencia": "TEXT",
            "valor_sh": "NUMERIC(14, 2) DEFAULT 0",
            "valor_sa": "NUMERIC(14, 2) DEFAULT 0",
            "valor_sp": "NUMERIC(14, 2) DEFAULT 0",
            "valor_total": "NUMERIC(14, 2) DEFAULT 0",
            "co_financiamento": "TEXT",
            "no_financiamento": "TEXT",
            "co_rubrica": "TEXT",
            "no_rubrica": "TEXT",
            "qtd_cids": "INTEGER DEFAULT 0",
            "cids_codigos": "TEXT",
            "cids_descricoes": "TEXT",
            "qtd_cbos": "INTEGER DEFAULT 0",
            "cbos_codigos": "TEXT",
            "cbos_descricoes": "TEXT",
            "qtd_servicos": "INTEGER DEFAULT 0",
            "servicos_codigos": "TEXT",
            "servicos_descricoes": "TEXT",
            "classificacoes_codigos": "TEXT",
            "classificacoes_descricoes": "TEXT",
            "criado_em": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
            "atualizado_em": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        }

        for col, col_type in alter_columns.items():
            cur.execute(f"""
                ALTER TABLE procedimentos
                ADD COLUMN IF NOT EXISTS {col} {col_type}
            """)

        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_procedimentos_codigo
            ON procedimentos (codigo)
        """)

        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_procedimentos_competencia
            ON procedimentos (competencia)
        """)

        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_procedimentos_complexidade
            ON procedimentos (complexidade)
        """)

        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_procedimentos_financiamento
            ON procedimentos (co_financiamento)
        """)

        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_procedimentos_rubrica
            ON procedimentos (co_rubrica)
        """)

        conn.commit()

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()


# =========================================================
# LISTAGEM / PESQUISA
# =========================================================
@procedimentos_bp.route("/")
def index():
    ensure_schema()

    q = normalize_text(request.args.get("q"))
    codigo = normalize_text(request.args.get("codigo"))
    descricao = normalize_text(request.args.get("descricao"))
    complexidade = normalize_text(request.args.get("complexidade"))
    competencia = normalize_text(request.args.get("competencia"))
    cid = normalize_text(request.args.get("cid"))
    cbo = normalize_text(request.args.get("cbo"))
    servico = normalize_text(request.args.get("servico"))
    financiamento = normalize_text(request.args.get("financiamento"))
    rubrica = normalize_text(request.args.get("rubrica"))

    pagina = max(1, request.args.get("pagina", 1, type=int))
    por_pagina = 12
    offset = (pagina - 1) * por_pagina

    conn = get_conn()

    try:
        cur = conn.cursor()

        where = ["1=1"]
        params = []

        if q:
            where.append("""
                (
                    codigo ILIKE %s OR
                    descricao ILIKE %s OR
                    cids_codigos ILIKE %s OR
                    cids_descricoes ILIKE %s OR
                    cbos_codigos ILIKE %s OR
                    cbos_descricoes ILIKE %s OR
                    servicos_codigos ILIKE %s OR
                    servicos_descricoes ILIKE %s OR
                    classificacoes_codigos ILIKE %s OR
                    classificacoes_descricoes ILIKE %s
                )
            """)
            like = safe_like(q)
            params.extend([like] * 10)

        if codigo:
            where.append("codigo ILIKE %s")
            params.append(safe_like(codigo))

        if descricao:
            where.append("descricao ILIKE %s")
            params.append(safe_like(descricao))

        if complexidade:
            where.append("complexidade ILIKE %s")
            params.append(safe_like(complexidade))

        if competencia:
            where.append("competencia ILIKE %s")
            params.append(safe_like(competencia))

        if cid:
            where.append("(cids_codigos ILIKE %s OR cids_descricoes ILIKE %s)")
            params.extend([safe_like(cid), safe_like(cid)])

        if cbo:
            where.append("(cbos_codigos ILIKE %s OR cbos_descricoes ILIKE %s)")
            params.extend([safe_like(cbo), safe_like(cbo)])

        if servico:
            where.append("""
                (
                    servicos_codigos ILIKE %s OR
                    servicos_descricoes ILIKE %s OR
                    classificacoes_codigos ILIKE %s OR
                    classificacoes_descricoes ILIKE %s
                )
            """)
            params.extend([safe_like(servico)] * 4)

        if financiamento:
            where.append("(co_financiamento ILIKE %s OR no_financiamento ILIKE %s)")
            params.extend([safe_like(financiamento), safe_like(financiamento)])

        if rubrica:
            where.append("(co_rubrica ILIKE %s OR no_rubrica ILIKE %s)")
            params.extend([safe_like(rubrica), safe_like(rubrica)])

        where_sql = " AND ".join(where)

        # TOTAL
        cur.execute(f"""
            SELECT COUNT(*)
            FROM procedimentos
            WHERE {where_sql}
        """, params)

        total = cur.fetchone()[0] or 0
        total_paginas = max(1, math.ceil(total / por_pagina))

        # DADOS
        cur.execute(f"""
            SELECT
                id,
                codigo,
                descricao,
                complexidade,
                competencia,
                valor_sh,
                valor_sa,
                valor_sp,
                valor_total,
                co_financiamento,
                no_financiamento,
                co_rubrica,
                no_rubrica,
                qtd_cids,
                cids_codigos,
                cids_descricoes,
                qtd_cbos,
                cbos_codigos,
                cbos_descricoes,
                qtd_servicos,
                servicos_codigos,
                servicos_descricoes,
                classificacoes_codigos,
                classificacoes_descricoes
            FROM procedimentos
            WHERE {where_sql}
            ORDER BY codigo ASC NULLS LAST, descricao ASC NULLS LAST
            LIMIT %s OFFSET %s
        """, params + [por_pagina, offset])

        rows = cur.fetchall()

        # 🔥 AQUI ESTÁ A CORREÇÃO
        cols = [desc[0] for desc in cur.description]
        dados = [dict(zip(cols, row)) for row in rows]

        filtros = {
            "q": q,
            "codigo": codigo,
            "descricao": descricao,
            "complexidade": complexidade,
            "competencia": competencia,
            "cid": cid,
            "cbo": cbo,
            "servico": servico,
            "financiamento": financiamento,
            "rubrica": rubrica,
        }

        return render_template(
            "proced.html",
            dados=dados,
            filtros=filtros,
            pagina=pagina,
            total_paginas=total_paginas,
            total=total,
        )

    finally:
        conn.close()
# =========================================================
# API - DETALHE DO PROCEDIMENTO
# =========================================================
@procedimentos_bp.route("/api/<int:procedimento_id>")
def api_detalhe(procedimento_id):
    ensure_schema()

    conn = get_conn()

    try:
        cur = conn.cursor()

        cur.execute("""
            SELECT
                id,
                codigo,
                descricao,
                complexidade,
                competencia,
                valor_sh,
                valor_sa,
                valor_sp,
                valor_total,
                co_financiamento,
                no_financiamento,
                co_rubrica,
                no_rubrica,
                qtd_cids,
                cids_codigos,
                cids_descricoes,
                qtd_cbos,
                cbos_codigos,
                cbos_descricoes,
                qtd_servicos,
                servicos_codigos,
                servicos_descricoes,
                classificacoes_codigos,
                classificacoes_descricoes
            FROM procedimentos
            WHERE id = %s
        """, (procedimento_id,))

        row = cur.fetchone()

        if not row:
            return jsonify({"ok": False, "erro": "Procedimento não encontrado"}), 404

        cols = [desc[0] for desc in cur.description]
        item = dict(zip(cols, row))

        return jsonify({"ok": True, "procedimento": item})

    finally:
        conn.close()


# =========================================================
# IMPORTAÇÃO XLSX
# =========================================================
@procedimentos_bp.route("/importar", methods=["POST"])
def importar_xls():
    ensure_schema()

    file = request.files.get("arquivo")

    if not file:
        flash("Arquivo não enviado.", "error")
        return redirect(url_for("procedimentos.index"))


    try:
        df = pd.read_excel(file, dtype=str).fillna("")
        df.columns = [normalize_text(c).lower() for c in df.columns]
    except Exception as e:
        flash(f"Erro ao ler arquivo: {e}", "error")
        return redirect(url_for("procedimentos.index"))

    conn = get_conn()

    try:
        cur = conn.cursor()

        # Importação substitutiva
        cur.execute("DELETE FROM procedimentos")

        total = 0

        for _, row in df.iterrows():
            valor_sh = to_float(get_col(row, "valor_sh", "vl_sh"))
            valor_sa = to_float(get_col(row, "valor_sa", "vl_sa"))
            valor_sp = to_float(get_col(row, "valor_sp", "vl_sp"))

            valor_total_planilha = to_float(get_col(row, "valor_total", "vl_total"))

            if valor_total_planilha > 0:
                valor_total = valor_total_planilha
            else:
                valor_total = valor_sh + valor_sa + valor_sp

            cur.execute("""
                INSERT INTO procedimentos (
                    codigo,
                    descricao,
                    complexidade,
                    competencia,

                    valor_sh,
                    valor_sa,
                    valor_sp,
                    valor_total,

                    co_financiamento,
                    no_financiamento,
                    co_rubrica,
                    no_rubrica,

                    qtd_cids,
                    cids_codigos,
                    cids_descricoes,

                    qtd_cbos,
                    cbos_codigos,
                    cbos_descricoes,

                    qtd_servicos,
                    servicos_codigos,
                    servicos_descricoes,

                    classificacoes_codigos,
                    classificacoes_descricoes,

                    atualizado_em
                )
                VALUES (
                    %s, %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s,
                    %s, %s,
                    CURRENT_TIMESTAMP
                )
            """, (
                normalize_text(get_col(row, "codigo", "co_procedimento")),
                normalize_text(get_col(row, "descricao", "no_procedimento")),
                normalize_text(get_col(row, "complexidade", "tp_complexidade")),
                normalize_text(get_col(row, "competencia", "dt_competencia")),

                valor_sh,
                valor_sa,
                valor_sp,
                valor_total,

                normalize_text(get_col(row, "co_financiamento")),
                normalize_text(get_col(row, "no_financiamento")),
                normalize_text(get_col(row, "co_rubrica")),
                normalize_text(get_col(row, "no_rubrica")),

                to_int(get_col(row, "qtd_cids")),
                normalize_text(get_col(row, "cids_codigos")),
                normalize_text(get_col(row, "cids_descricoes")),

                to_int(get_col(row, "qtd_cbos")),
                normalize_text(get_col(row, "cbos_codigos")),
                normalize_text(get_col(row, "cbos_descricoes")),

                to_int(get_col(row, "qtd_servicos")),
                normalize_text(get_col(row, "servicos_codigos")),
                normalize_text(get_col(row, "servicos_descricoes")),

                normalize_text(get_col(row, "classificacoes_codigos")),
                normalize_text(get_col(row, "classificacoes_descricoes")),
            ))

            total += 1

        conn.commit()
        flash(f"{total} procedimentos importados com sucesso.", "success")

    except Exception as e:
        conn.rollback()
        flash(f"Erro na importação: {e}", "error")

    finally:
        conn.close()

    return redirect(url_for("procedimentos.index"))


# =========================================================
# EXCLUSÃO INDIVIDUAL
# =========================================================
@procedimentos_bp.route("/excluir/<int:procedimento_id>", methods=["POST"])
def excluir(procedimento_id):
    ensure_schema()

    conn = get_conn()

    try:
        cur = conn.cursor()

        cur.execute("DELETE FROM procedimentos WHERE id = %s", (procedimento_id,))

        if cur.rowcount == 0:
            flash("Procedimento não encontrado.", "warning")
        else:
            flash("Procedimento excluído com sucesso.", "success")

        conn.commit()

    except Exception as e:
        conn.rollback()
        flash(f"Erro ao excluir procedimento: {e}", "error")

    finally:
        conn.close()

    return redirect(url_for("procedimentos.index"))


# =========================================================
# LIMPAR BASE
# =========================================================
@procedimentos_bp.route("/limpar", methods=["POST"])
def limpar():
    ensure_schema()

    conn = get_conn()

    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM procedimentos")
        conn.commit()

        flash("Base de procedimentos limpa com sucesso.", "success")

    except Exception as e:
        conn.rollback()
        flash(f"Erro ao limpar base: {e}", "error")

    finally:
        conn.close()

    return redirect(url_for("procedimentos.index"))


# =========================================================
# EXPORTAÇÃO XLSX DOS FILTROS
# =========================================================
@procedimentos_bp.route("/exportar", methods=["GET"])
def exportar():
    ensure_schema()

    q = normalize_text(request.args.get("q"))
    codigo = normalize_text(request.args.get("codigo"))
    descricao = normalize_text(request.args.get("descricao"))
    complexidade = normalize_text(request.args.get("complexidade"))
    competencia = normalize_text(request.args.get("competencia"))
    cid = normalize_text(request.args.get("cid"))
    cbo = normalize_text(request.args.get("cbo"))
    servico = normalize_text(request.args.get("servico"))
    financiamento = normalize_text(request.args.get("financiamento"))
    rubrica = normalize_text(request.args.get("rubrica"))

    conn = get_conn()

    try:
        cur = conn.cursor()

        where = ["1=1"]
        params = []

        if q:
            where.append("""
                (
                    codigo ILIKE %s OR
                    descricao ILIKE %s OR
                    cids_codigos ILIKE %s OR
                    cids_descricoes ILIKE %s OR
                    cbos_codigos ILIKE %s OR
                    cbos_descricoes ILIKE %s OR
                    servicos_codigos ILIKE %s OR
                    servicos_descricoes ILIKE %s OR
                    classificacoes_codigos ILIKE %s OR
                    classificacoes_descricoes ILIKE %s
                )
            """)
            like = safe_like(q)
            params.extend([like] * 10)

        if codigo:
            where.append("codigo ILIKE %s")
            params.append(safe_like(codigo))

        if descricao:
            where.append("descricao ILIKE %s")
            params.append(safe_like(descricao))

        if complexidade:
            where.append("complexidade ILIKE %s")
            params.append(safe_like(complexidade))

        if competencia:
            where.append("competencia ILIKE %s")
            params.append(safe_like(competencia))

        if cid:
            where.append("(cids_codigos ILIKE %s OR cids_descricoes ILIKE %s)")
            params.extend([safe_like(cid), safe_like(cid)])

        if cbo:
            where.append("(cbos_codigos ILIKE %s OR cbos_descricoes ILIKE %s)")
            params.extend([safe_like(cbo), safe_like(cbo)])

        if servico:
            where.append("""
                (
                    servicos_codigos ILIKE %s OR
                    servicos_descricoes ILIKE %s OR
                    classificacoes_codigos ILIKE %s OR
                    classificacoes_descricoes ILIKE %s
                )
            """)
            params.extend([safe_like(servico)] * 4)

        if financiamento:
            where.append("(co_financiamento ILIKE %s OR no_financiamento ILIKE %s)")
            params.extend([safe_like(financiamento), safe_like(financiamento)])

        if rubrica:
            where.append("(co_rubrica ILIKE %s OR no_rubrica ILIKE %s)")
            params.extend([safe_like(rubrica), safe_like(rubrica)])

        where_sql = " AND ".join(where)

        cur.execute(f"""
            SELECT
                codigo,
                descricao,
                complexidade,
                competencia,
                valor_sh,
                valor_sa,
                valor_sp,
                valor_total,
                co_financiamento,
                no_financiamento,
                co_rubrica,
                no_rubrica,
                qtd_cids,
                cids_codigos,
                cids_descricoes,
                qtd_cbos,
                cbos_codigos,
                cbos_descricoes,
                qtd_servicos,
                servicos_codigos,
                servicos_descricoes,
                classificacoes_codigos,
                classificacoes_descricoes
            FROM procedimentos
            WHERE {where_sql}
            ORDER BY codigo ASC NULLS LAST, descricao ASC NULLS LAST
        """, params)

        rows = cur.fetchall()
        cols = [desc[0] for desc in cur.description]

        df = pd.DataFrame(rows, columns=cols)

        mem = BytesIO()

        with pd.ExcelWriter(mem, engine="openpyxl") as writer:
            df.to_excel(writer, index=False, sheet_name="procedimentos")

        mem.seek(0)

        return send_file(
            mem,
            as_attachment=True,
            download_name="procedimentos_filtrados.xlsx",
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

    finally:
        conn.close()

# =========================================================
# PESQUISA EM LOTE
# =========================================================
@procedimentos_bp.route("/lote", methods=["GET", "POST"])
def lote():
    ensure_schema()

    resultados = []
    total_enviados = 0
    total_encontrados = 0

    if request.method == "POST":
        texto = request.form.get("codigos", "") or ""
        codigos = [
            normalize_text(c)
            for c in re.split(r"[\n,; ]+", texto)
            if normalize_text(c)
        ]

        total_enviados = len(codigos)

        if codigos:
            conn = get_conn()

            try:
                cur = conn.cursor()

                for codigo in codigos:
                    cur.execute("""
                        SELECT
                            id,
                            codigo,
                            descricao,
                            complexidade,
                            competencia,
                            valor_sh,
                            valor_sa,
                            valor_sp,
                            valor_total,
                            co_financiamento,
                            no_financiamento,
                            co_rubrica,
                            no_rubrica,
                            qtd_cids,
                            cids_codigos,
                            cids_descricoes,
                            qtd_cbos,
                            cbos_codigos,
                            cbos_descricoes,
                            qtd_servicos,
                            servicos_codigos,
                            servicos_descricoes,
                            classificacoes_codigos,
                            classificacoes_descricoes
                        FROM procedimentos
                        WHERE codigo = %s
                        LIMIT 1
                    """, (codigo,))

                    row = cur.fetchone()

                    if row:
                        cols = [desc[0] for desc in cur.description]
                        item = dict(zip(cols, row))
                        item["encontrado"] = True
                        resultados.append(item)
                        total_encontrados += 1
                    else:
                        resultados.append({
                            "codigo": codigo,
                            "descricao": "Não encontrado",
                            "encontrado": False
                        })

            finally:
                conn.close()

    return render_template(
        "proced_lote.html",
        resultados=resultados,
        total_enviados=total_enviados,
        total_encontrados=total_encontrados
    )

# =========================================================
# LIMPAR BANCO - ALIAS PARA COMPATIBILIDADE COM O TEMPLATE
# =========================================================
@procedimentos_bp.route("/limpar-banco", methods=["POST"])
def limpar_banco():
    return limpar()