# admin/users.py
from __future__ import annotations

from datetime import datetime
import json

from flask import render_template, request, redirect, url_for, flash, jsonify, session, abort, g
from werkzeug.security import generate_password_hash

from . import admin_bp, admin_required
from .helpers import db_conn, only_digits, list_columns

try:
    from .modulos import require_permission, usuario_eh_master, get_clinica_id_contexto
except Exception:
    def require_permission(modulo_codigo: str, acao: str = "ver"):
        def deco(fn):
            return fn
        return deco

    def usuario_eh_master():
        return bool(session.get("is_master") or session.get("is_superuser"))

    def get_clinica_id_contexto(default=1):
        return int(session.get("clinica_id") or default)

try:
    from log import registrar_log, log_erro, log_criacao, log_edicao, log_exclusao
except Exception:
    def registrar_log(*args, **kwargs): pass
    def log_erro(*args, **kwargs): pass
    def log_criacao(*args, **kwargs): pass
    def log_edicao(*args, **kwargs): pass
    def log_exclusao(*args, **kwargs): pass


NIVEIS = [
    {
        "slug": "ADMIN",
        "nome": "Administrador",
        "permissoes": [
            "cadastro", "pacientes", "atendimentos", "agenda",
            "export_bpai", "export_apac", "export_ciha",
            "financeiro", "rh"
        ],
    },
    {
        "slug": "RECEPCAO",
        "nome": "Recepção",
        "permissoes": ["cadastro", "pacientes", "atendimentos", "agenda"],
    },
    {
        "slug": "PROFISSIONAL",
        "nome": "Profissional",
        "permissoes": ["pacientes", "atendimentos", "agenda"],
    },
]


# =============================================================================
# HELPERS
# =============================================================================

def _fetchall_as_dicts(cur):
    rows = cur.fetchall() or []
    out = []

    for row in rows:
        if isinstance(row, dict):
            out.append(dict(row))
            continue

        try:
            out.append(dict(row))
            continue
        except Exception:
            pass

        cols = [c[0] for c in cur.description] if cur.description else []
        out.append(dict(zip(cols, row)))

    return out


def _fetchone_as_dict(cur):
    row = cur.fetchone()

    if row is None:
        return None

    if isinstance(row, dict):
        return dict(row)

    try:
        return dict(row)
    except Exception:
        pass

    cols = [c[0] for c in cur.description] if cur.description else []
    return dict(zip(cols, row))


def _normalize_bool(v) -> bool:
    if isinstance(v, bool):
        return v

    return str(v).strip().lower() in {"1", "true", "t", "yes", "sim", "ativo", "on"}


def _nz(v):
    v = (v or "").strip()
    return v if v else None


def _integrity_error_class():
    try:
        import psycopg
        return psycopg.IntegrityError
    except Exception:
        pass

    try:
        import psycopg2
        return psycopg2.IntegrityError
    except Exception:
        pass

    return Exception


def _current_user_id():
    return session.get("usuario_id") or session.get("user_id")


def _current_clinica_id():
    return int(session.get("clinica_id") or get_clinica_id_contexto() or 1)


def _normalizar_role(role: str | None) -> str:
    role = (role or "").strip().upper()

    if role == "RECEPÇÃO":
        return "RECEPCAO"

    if role == "PROFISSIONAIS":
        return "PROFISSIONAL"

    if role not in {"ADMIN", "RECEPCAO", "PROFISSIONAL", "MASTER", "ROOT", "SUPERADMIN"}:
        return "RECEPCAO"

    return role


def _usuario_pode_manipular_clinica(clinica_id: int) -> bool:
    if usuario_eh_master():
        return True

    return int(session.get("clinica_id") or 0) == int(clinica_id or 0)


def _resolver_clinica_alvo():
    """
    Regra:
    - MASTER usa a clínica escolhida no painel pós-login.
    - Usuário comum usa a própria clínica da sessão.
    """
    clinica_id = _current_clinica_id()

    if not clinica_id:
        abort(403)

    return int(clinica_id)


def _row_id(row):
    if isinstance(row, dict):
        return row.get("id")
    return row[0]


# =============================================================================
# SCHEMA
# =============================================================================

def ensure_users_table():
    cache_key = "_ensure_users_table_ok"

    if getattr(g, cache_key, False):
        return

    conn = db_conn(False)

    try:
        try:
            conn.rollback()
        except Exception:
            pass

        cur = conn.cursor()

        cur.execute("""
            CREATE TABLE IF NOT EXISTS usuarios (
                id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome              TEXT,
                email             TEXT,
                cpf               TEXT,
                cpf_digits        TEXT,
                cns               TEXT,
                nascimento        TEXT,
                sexo              TEXT,
                conselho          TEXT,
                registro_conselho TEXT,
                uf_conselho       TEXT,
                cbo               TEXT,
                cbo_descricao     TEXT,
                telefone          TEXT,
                role              TEXT,
                is_active         BOOLEAN DEFAULT TRUE,
                clinica_id        INTEGER,
                perfil_id         INTEGER,
                is_master         BOOLEAN DEFAULT FALSE,
                is_superuser      BOOLEAN DEFAULT FALSE,
                cep               TEXT,
                logradouro        TEXT,
                numero            TEXT,
                complemento       TEXT,
                bairro            TEXT,
                municipio         TEXT,
                uf                TEXT,
                permissoes_json   TEXT,
                senha_hash        TEXT,
                password_hash     TEXT,
                criado_em         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                atualizado_em     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """)

        cols = list_columns(conn, "usuarios")

        def add_col(name: str, ddl: str):
            nonlocal cols
            if name not in cols:
                cur.execute(f"ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS {ddl};")
                conn.commit()
                cols = list_columns(conn, "usuarios")

        add_col("nome", "nome TEXT")
        add_col("email", "email TEXT")
        add_col("cpf", "cpf TEXT")
        add_col("cpf_digits", "cpf_digits TEXT")
        add_col("cns", "cns TEXT")
        add_col("nascimento", "nascimento TEXT")
        add_col("sexo", "sexo TEXT")
        add_col("conselho", "conselho TEXT")
        add_col("registro_conselho", "registro_conselho TEXT")
        add_col("uf_conselho", "uf_conselho TEXT")
        add_col("cbo", "cbo TEXT")
        add_col("cbo_descricao", "cbo_descricao TEXT")
        add_col("telefone", "telefone TEXT")
        add_col("role", "role TEXT")
        add_col("is_active", "is_active BOOLEAN DEFAULT TRUE")
        add_col("clinica_id", "clinica_id INTEGER")
        add_col("perfil_id", "perfil_id INTEGER")
        add_col("is_master", "is_master BOOLEAN DEFAULT FALSE")
        add_col("is_superuser", "is_superuser BOOLEAN DEFAULT FALSE")
        add_col("cep", "cep TEXT")
        add_col("logradouro", "logradouro TEXT")
        add_col("numero", "numero TEXT")
        add_col("complemento", "complemento TEXT")
        add_col("bairro", "bairro TEXT")
        add_col("municipio", "municipio TEXT")
        add_col("uf", "uf TEXT")
        add_col("permissoes_json", "permissoes_json TEXT")
        add_col("senha_hash", "senha_hash TEXT")
        add_col("password_hash", "password_hash TEXT")
        add_col("criado_em", "criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
        add_col("atualizado_em", "atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP")

        cur.execute("""
            UPDATE usuarios
               SET cpf_digits = REGEXP_REPLACE(COALESCE(cpf, ''), '[^0-9]', '', 'g')
             WHERE cpf IS NOT NULL
               AND (cpf_digits IS NULL OR BTRIM(cpf_digits) = '');
        """)

        cur.execute("""
            UPDATE usuarios
               SET criado_em = CURRENT_TIMESTAMP
             WHERE criado_em IS NULL;
        """)

        cur.execute("""
            UPDATE usuarios
               SET atualizado_em = CURRENT_TIMESTAMP
             WHERE atualizado_em IS NULL;
        """)

        cur.execute("""
            UPDATE usuarios
               SET password_hash = senha_hash
             WHERE (password_hash IS NULL OR BTRIM(password_hash) = '')
               AND (senha_hash IS NOT NULL AND BTRIM(senha_hash) <> '');
        """)

        cur.execute("""
            UPDATE usuarios
               SET senha_hash = password_hash
             WHERE (senha_hash IS NULL OR BTRIM(senha_hash) = '')
               AND (password_hash IS NOT NULL AND BTRIM(password_hash) <> '');
        """)

        # Remove índices globais antigos.
        cur.execute("DROP INDEX IF EXISTS idx_usuarios_email;")
        cur.execute("DROP INDEX IF EXISTS idx_usuarios_cpf;")
        cur.execute("DROP INDEX IF EXISTS idx_usuarios_cpf_digits;")

        # Índices multi-clínica.
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_usuarios_clinica_id
                ON usuarios(clinica_id);
        """)

        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_usuarios_clinica_role
                ON usuarios(clinica_id, role);
        """)

        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_usuarios_active
                ON usuarios(is_active);
        """)

        cur.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_clinica_cpf_digits
                ON usuarios(clinica_id, cpf_digits)
                WHERE clinica_id IS NOT NULL
                  AND cpf_digits IS NOT NULL
                  AND BTRIM(cpf_digits) <> '';
        """)

        cur.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_clinica_email
                ON usuarios(clinica_id, email)
                WHERE clinica_id IS NOT NULL
                  AND email IS NOT NULL
                  AND BTRIM(email) <> '';
        """)

        conn.commit()
        setattr(g, cache_key, True)

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()

# =============================================================================
# CBO
# =============================================================================

def get_cbo_descricao(codigo: str | None) -> str:
    codigo = only_digits(codigo)[:6]

    if not codigo:
        return ""

    cache_key = f"cbo_desc_{codigo}"

    if hasattr(g, cache_key):
        return getattr(g, cache_key)

    conn = db_conn(True)

    try:
        cur = conn.cursor()

        try:
            cur.execute("""
                SELECT BTRIM(COALESCE(descricao, '')) AS descricao
                  FROM cbo_catalogo
                 WHERE BTRIM(COALESCE(codigo, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            row = _fetchone_as_dict(cur)

            if row and (row.get("descricao") or "").strip():
                desc = row["descricao"].strip()
                setattr(g, cache_key, desc)
                return desc

        except Exception:
            conn.rollback()

        try:
            cur.execute("""
                SELECT BTRIM(COALESCE(no_ocupacao, '')) AS descricao
                  FROM ocupacoes
                 WHERE BTRIM(COALESCE(co_ocupacao, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            row = _fetchone_as_dict(cur)

            desc = (row.get("descricao") or "").strip() if row else ""
            setattr(g, cache_key, desc)
            return desc

        except Exception:
            conn.rollback()
            setattr(g, cache_key, "")
            return ""

    finally:
        conn.close()


def cbo_existe_no_catalogo(codigo: str | None) -> bool:
    codigo = only_digits(codigo)[:6]

    if not codigo:
        return False

    cache_key = f"cbo_existe_{codigo}"

    if hasattr(g, cache_key):
        return getattr(g, cache_key)

    conn = db_conn(True)

    try:
        cur = conn.cursor()

        try:
            cur.execute("""
                SELECT 1
                  FROM cbo_catalogo
                 WHERE BTRIM(COALESCE(codigo, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            if cur.fetchone():
                setattr(g, cache_key, True)
                return True

        except Exception:
            conn.rollback()

        try:
            cur.execute("""
                SELECT 1
                  FROM ocupacoes
                 WHERE BTRIM(COALESCE(co_ocupacao, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            ok = cur.fetchone() is not None
            setattr(g, cache_key, ok)
            return ok

        except Exception:
            conn.rollback()
            setattr(g, cache_key, False)
            return False

    finally:
        conn.close()


def get_cbos_catalogo_local(q: str | None = None, limit: int = 200):
    cache_key = f"cbos_catalogo_{(q or '').strip().lower()}_{limit}"

    if hasattr(g, cache_key):
        return getattr(g, cache_key)

    conn = db_conn(True)

    try:
        cur = conn.cursor()
        q_norm = (q or "").strip()
        q_digits = only_digits(q_norm)

        def montar_items(rows):
            return [
                {
                    "id": (r.get("codigo") or "").strip(),
                    "codigo": (r.get("codigo") or "").strip(),
                    "descricao": (r.get("descricao") or "").strip(),
                    "label": f"{(r.get('codigo') or '').strip()} - {(r.get('descricao') or '').strip()}".strip(" -"),
                }
                for r in rows
                if (r.get("codigo") or "").strip()
            ]

        try:
            sql = """
                SELECT
                    BTRIM(COALESCE(codigo, '')) AS codigo,
                    BTRIM(COALESCE(descricao, '')) AS descricao
                  FROM cbo_catalogo
                 WHERE BTRIM(COALESCE(codigo, '')) <> ''
            """
            params = []

            if q_norm:
                sql += """
                   AND (
                        CAST(codigo AS TEXT) ILIKE %s
                        OR COALESCE(descricao, '') ILIKE %s
                   )
                """
                params.extend([f"%{q_digits or q_norm}%", f"%{q_norm}%"])

            sql += " ORDER BY codigo ASC LIMIT %s;"
            params.append(int(limit))

            cur.execute(sql, params)
            items = montar_items(_fetchall_as_dicts(cur))

            if items:
                setattr(g, cache_key, items)
                return items

        except Exception:
            conn.rollback()

        try:
            sql = """
                SELECT
                    BTRIM(COALESCE(co_ocupacao, '')) AS codigo,
                    BTRIM(COALESCE(no_ocupacao, '')) AS descricao
                  FROM ocupacoes
                 WHERE BTRIM(COALESCE(co_ocupacao, '')) <> ''
            """
            params = []

            if q_norm:
                sql += """
                   AND (
                        CAST(co_ocupacao AS TEXT) ILIKE %s
                        OR COALESCE(no_ocupacao, '') ILIKE %s
                   )
                """
                params.extend([f"%{q_digits or q_norm}%", f"%{q_norm}%"])

            sql += " ORDER BY codigo ASC LIMIT %s;"
            params.append(int(limit))

            cur.execute(sql, params)
            items = montar_items(_fetchall_as_dicts(cur))
            setattr(g, cache_key, items)
            return items

        except Exception:
            conn.rollback()
            setattr(g, cache_key, [])
            return []

    finally:
        conn.close()


# =============================================================================
# USER HELPERS
# =============================================================================

def load_user(uid: int, exigir_mesma_clinica=True):
    ensure_users_table()

    conn = db_conn(True)

    try:
        cur = conn.cursor()

        params = [uid]
        filtro = ""

        if exigir_mesma_clinica and not usuario_eh_master():
            filtro = "AND COALESCE(clinica_id, 1) = %s"
            params.append(_current_clinica_id())

        cur.execute(f"""
            SELECT *
              FROM usuarios
             WHERE id = %s
               {filtro}
             LIMIT 1;
        """, params)

        return _fetchone_as_dict(cur)

    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        raise

    finally:
        try:
            conn.close()
        except Exception:
            pass


def _montar_permissoes_json():
    permissoes = []

    for k in request.form.keys():
        if k.startswith("perm_") and request.form.get(k) == "1":
            permissoes.append(k.replace("perm_", "", 1))

    return json.dumps(permissoes, ensure_ascii=False) if permissoes else None


def _montar_payload_usuario(row_atual=None):
    nome = (request.form.get("nome") or "").strip()
    cpf = (request.form.get("cpf") or "").strip()
    role = _normalizar_role((request.form.get("role") or "").strip() or (row_atual or {}).get("role") or "RECEPCAO")
    is_active_raw = request.form.get("is_active") or "1"

    if not nome or not cpf or not role:
        raise ValueError("Preencha ao menos Nome, CPF e Nível.")

    cpf_digits = only_digits(cpf)

    if len(cpf_digits) != 11:
        raise ValueError("CPF inválido. Informe 11 dígitos.")

    if role in {"MASTER", "ROOT", "SUPERADMIN"} and not usuario_eh_master():
        raise PermissionError("Apenas o Master pode criar ou editar usuário Master.")

    cbo = _nz(only_digits(request.form.get("cbo"))[:6])

    if cbo and not cbo_existe_no_catalogo(cbo):
        raise ValueError("O CBO informado não existe no catálogo local.")

    cbo_descricao = get_cbo_descricao(cbo) if cbo else None

    clinica_id = _resolver_clinica_alvo()

    return {
        "nome": nome,
        "email": _nz(request.form.get("email")),
        "cpf": cpf,
        "cpf_digits": cpf_digits,
        "cns": _nz(request.form.get("cns")),
        "nascimento": _nz(request.form.get("nascimento")),
        "sexo": _nz(request.form.get("sexo")),
        "conselho": _nz(request.form.get("conselho")),
        "registro_conselho": _nz(request.form.get("registro_conselho")),
        "uf_conselho": _nz(request.form.get("uf_conselho")),
        "cbo": cbo,
        "cbo_descricao": cbo_descricao,
        "telefone": _nz(request.form.get("telefone")),
        "role": role,
        "is_active": str(is_active_raw) == "1",
        "clinica_id": clinica_id,
        "cep": _nz(request.form.get("cep")),
        "logradouro": _nz(request.form.get("logradouro")),
        "numero": _nz(request.form.get("numero")),
        "complemento": _nz(request.form.get("complemento")),
        "bairro": _nz(request.form.get("bairro")),
        "municipio": _nz(request.form.get("municipio")),
        "uf": _nz(request.form.get("uf")),
        "permissoes_json": _montar_permissoes_json(),
        "is_master": role in {"MASTER", "ROOT", "SUPERADMIN"},
        "is_superuser": role in {"MASTER", "ROOT", "SUPERADMIN"},
    }


def _redirect_usuarios():
    return redirect(url_for("admin.usuarios_listar"))


# =============================================================================
# API CBO
# =============================================================================

@admin_bp.route("/api/cbos-catalogo/buscar")
@admin_required
@require_permission("admin_usuarios", "ver")
def cbos_catalogo_buscar():
    q = (request.args.get("q") or "").strip()

    if len(q) < 2:
        return jsonify({"ok": True, "q": q, "items": []})

    items = get_cbos_catalogo_local(q=q, limit=20)
    return jsonify({"ok": True, "q": q, "items": items})


# =============================================================================
# DASHBOARD
# =============================================================================

@admin_bp.route("/")
@admin_required
@require_permission("admin_painel", "ver")
def admin_home():
    total_usuarios = 0
    usuarios_ativos = 0
    clinica_id = _current_clinica_id()

    conn = None

    try:
        ensure_users_table()

        conn = db_conn(True)
        cur = conn.cursor()

        cur.execute("""
            SELECT
                COUNT(1) AS total_usuarios,
                SUM(CASE WHEN COALESCE(is_active, FALSE) = TRUE THEN 1 ELSE 0 END) AS usuarios_ativos
              FROM usuarios
             WHERE COALESCE(clinica_id, 1) = %s;
        """, (clinica_id,))

        row = _fetchone_as_dict(cur) or {}

        total_usuarios = int(row.get("total_usuarios") or 0)
        usuarios_ativos = int(row.get("usuarios_ativos") or 0)

        log_visualizacao = registrar_log
        log_visualizacao(
            modulo="admin_painel",
            acao="visualizar",
            entidade="admin",
            descricao="Visualizou painel administrativo.",
            detalhes={"clinica_id": clinica_id},
        )

    except Exception as e:
        if conn:
            conn.rollback()

        log_erro(
            "admin_painel",
            e,
            descricao="Erro ao carregar painel administrativo.",
            detalhes={"clinica_id": clinica_id},
        )

    finally:
        if conn:
            conn.close()

    ctx = {
        "total_usuarios": total_usuarios,
        "usuarios_ativos": usuarios_ativos,
        "modulos_habilitados": 3,
        "ultimo_backup": datetime.now().strftime("%d/%m/%Y %H:%M"),
        "clinica_id": clinica_id,
        "clinica_nome": session.get("clinica_nome"),
    }

    return render_template("admin.html", **ctx)


# =============================================================================
# USUÁRIOS - LISTAR
# =============================================================================

@admin_bp.route("/usuarios")
@admin_required
@require_permission("admin_usuarios", "ver")
def usuarios_listar():
    usuarios = []
    conn = None
    clinica_id = _current_clinica_id()

    try:
        ensure_users_table()

        conn = db_conn(True)

        try:
            conn.rollback()
        except Exception:
            pass

        cur = conn.cursor()

        cur.execute("""
            SELECT
                id,
                nome,
                cpf,
                cpf_digits,
                email,
                role,
                is_active,
                criado_em,
                cbo,
                cbo_descricao,
                clinica_id
              FROM usuarios
             WHERE clinica_id = %s
               AND COALESCE(is_master, FALSE) = FALSE
               AND COALESCE(is_superuser, FALSE) = FALSE
             ORDER BY id DESC;
        """, (clinica_id,))

        rows = _fetchall_as_dicts(cur)

        for r in rows:
            cbo_codigo = (r.get("cbo") or "").strip()
            cbo_descricao = (r.get("cbo_descricao") or "").strip()

            usuarios.append({
                "id": r.get("id"),
                "nome": r.get("nome"),
                "cpf": r.get("cpf"),
                "cpf_digits": r.get("cpf_digits"),
                "email": r.get("email"),
                "role": r.get("role"),
                "is_active": _normalize_bool(r.get("is_active")),
                "criado_em": r.get("criado_em"),
                "cbo": cbo_codigo,
                "cbo_descricao": cbo_descricao,
                "cbo_label": (
                    f"{cbo_codigo} — {cbo_descricao}"
                    if cbo_codigo and cbo_descricao
                    else (cbo_codigo or "—")
                ),
                "clinica_id": r.get("clinica_id"),
            })

        registrar_log(
            modulo="admin_usuarios",
            acao="visualizar",
            entidade="usuarios",
            descricao="Visualizou lista de usuários.",
            detalhes={
                "clinica_id": clinica_id,
                "total": len(usuarios),
            },
        )

    except Exception as e:
        if conn:
            conn.rollback()

        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            descricao="Falha ao carregar usuários.",
            detalhes={"clinica_id": clinica_id},
        )

        flash(f"Falha ao carregar usuários: {e}", "error")

    finally:
        if conn:
            conn.close()

    return render_template(
        "admin-usuarios.html",
        usuarios=usuarios,
        niveis=NIVEIS,
        cbos_catalogo=get_cbos_catalogo_local(limit=120),
        clinica_id=clinica_id,
        clinica_nome=session.get("clinica_nome"),
        is_master=usuario_eh_master(),
    )

# =============================================================================
# USUÁRIOS - CRIAR
# =============================================================================

@admin_bp.route("/usuarios/novo", methods=["GET", "POST"])
@admin_required
@require_permission("admin_usuarios", "editar")
def usuarios_criar():
    if request.method != "POST":
        return redirect(url_for("admin.usuarios_listar"))

    conn = None
    clinica_id = _resolver_clinica_alvo()

    try:
        payload = _montar_payload_usuario()

        senha = request.form.get("senha") or ""
        senha2 = request.form.get("senha2") or ""

        if not senha or len(senha) < 6:
            raise ValueError("Defina uma senha com pelo menos 6 caracteres.")

        if senha != senha2:
            raise ValueError("A confirmação da senha não confere.")

        senha_hash = generate_password_hash(
            senha,
            method="pbkdf2:sha256",
            salt_length=16,
        )

        ensure_users_table()

        conn = db_conn(False)
        cur = conn.cursor()

        cur.execute("""
            INSERT INTO usuarios (
                nome,
                email,
                cpf,
                cpf_digits,
                cns,
                nascimento,
                sexo,
                conselho,
                registro_conselho,
                uf_conselho,
                cbo,
                cbo_descricao,
                telefone,
                role,
                is_active,
                clinica_id,
                is_master,
                is_superuser,
                cep,
                logradouro,
                numero,
                complemento,
                bairro,
                municipio,
                uf,
                permissoes_json,
                senha_hash,
                password_hash,
                criado_em,
                atualizado_em
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s,
                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            )
            RETURNING id;
        """, (
            payload["nome"],
            payload["email"],
            payload["cpf"],
            payload["cpf_digits"],
            payload["cns"],
            payload["nascimento"],
            payload["sexo"],
            payload["conselho"],
            payload["registro_conselho"],
            payload["uf_conselho"],
            payload["cbo"],
            payload["cbo_descricao"],
            payload["telefone"],
            payload["role"],
            payload["is_active"],
            payload["clinica_id"],
            payload["is_master"],
            payload["is_superuser"],
            payload["cep"],
            payload["logradouro"],
            payload["numero"],
            payload["complemento"],
            payload["bairro"],
            payload["municipio"],
            payload["uf"],
            payload["permissoes_json"],
            senha_hash,
            senha_hash,
        ))

        novo_id = _row_id(cur.fetchone())
        conn.commit()

        log_criacao(
            modulo="admin_usuarios",
            entidade="usuarios",
            entidade_id=novo_id,
            descricao="Usuário criado.",
            detalhes={
                "clinica_id": clinica_id,
                "nome": payload["nome"],
                "role": payload["role"],
            },
        )

        flash("Usuário criado com sucesso.", "success")
        return _redirect_usuarios()

    except _integrity_error_class() as e:
        if conn:
            conn.rollback()

        msg = str(e).lower()

        if "cpf_digits" in msg or "idx_usuarios_cpf_digits" in msg or "usuarios_cpf_key" in msg:
            flash("Já existe um usuário com esse CPF.", "error")
        elif "idx_usuarios_email" in msg or "usuarios_email_key" in msg:
            flash("Já existe um usuário com esse e-mail.", "error")
        else:
            flash(f"Erro de integridade ao salvar o usuário: {e}", "error")

        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            descricao="Erro de integridade ao criar usuário.",
            detalhes={"clinica_id": clinica_id},
        )

        return _redirect_usuarios()

    except Exception as e:
        if conn:
            conn.rollback()

        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            descricao="Erro ao criar usuário.",
            detalhes={"clinica_id": clinica_id},
        )

        flash(f"Erro ao criar usuário: {e}", "error")
        return _redirect_usuarios()

    finally:
        if conn:
            conn.close()


# =============================================================================
# USUÁRIOS - JSON
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>.json")
@admin_required
@require_permission("admin_usuarios", "ver")
def usuarios_json(uid):
    try:
        row = load_user(uid)

        if not row:
            return jsonify({"error": "Usuário não encontrado"}), 404

        data = dict(row)

        data.pop("senha_hash", None)
        data.pop("password_hash", None)

        for campo in ("criado_em", "atualizado_em", "nascimento", "last_login_at", "created_at"):
            if campo in data and data[campo] is not None:
                try:
                    data[campo] = data[campo].isoformat()
                except Exception:
                    data[campo] = str(data[campo])

        data["is_active"] = _normalize_bool(data.get("is_active"))

        cbo_codigo = (data.get("cbo") or "").strip()
        cbo_descricao = (data.get("cbo_descricao") or "").strip()

        if cbo_codigo and not cbo_descricao:
            cbo_descricao = get_cbo_descricao(cbo_codigo)

        data["cbo_descricao"] = cbo_descricao
        data["cbo_label"] = (
            f"{cbo_codigo} — {cbo_descricao}"
            if cbo_codigo and cbo_descricao
            else (cbo_codigo or "")
        )

        registrar_log(
            modulo="admin_usuarios",
            acao="visualizar",
            entidade="usuarios",
            entidade_id=uid,
            descricao="Carregou JSON de usuário.",
            detalhes={"clinica_id": _current_clinica_id()},
        )

        return jsonify(data)

    except Exception as e:
        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            entidade_id=uid,
            descricao="Erro ao carregar JSON de usuário.",
        )
        return jsonify({"error": str(e)}), 500


# =============================================================================
# USUÁRIOS - EDITAR
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>/editar", methods=["POST"])
@admin_required
@require_permission("admin_usuarios", "editar")
def usuarios_editar(uid):
    conn = None
    clinica_id = _current_clinica_id()

    try:
        row = load_user(uid)

        if not row:
            flash("Usuário não encontrado.", "error")
            return _redirect_usuarios()

        if not _usuario_pode_manipular_clinica(row.get("clinica_id")):
            abort(403)

        payload = _montar_payload_usuario(row)

        conn = db_conn(False)

        try:
            conn.rollback()
        except Exception:
            pass

        cur = conn.cursor()

        cur.execute("""
            UPDATE usuarios SET
                nome = %s,
                email = %s,
                cpf = %s,
                cpf_digits = %s,
                cns = %s,
                nascimento = %s,
                sexo = %s,
                conselho = %s,
                registro_conselho = %s,
                uf_conselho = %s,
                cbo = %s,
                cbo_descricao = %s,
                telefone = %s,
                role = %s,
                is_active = %s,
                clinica_id = %s,
                is_master = %s,
                is_superuser = %s,
                cep = %s,
                logradouro = %s,
                numero = %s,
                complemento = %s,
                bairro = %s,
                municipio = %s,
                uf = %s,
                permissoes_json = %s,
                atualizado_em = CURRENT_TIMESTAMP
            WHERE id = %s
              AND COALESCE(clinica_id, 1) = %s;
        """, (
            payload["nome"],
            payload["email"],
            payload["cpf"],
            payload["cpf_digits"],
            payload["cns"],
            payload["nascimento"],
            payload["sexo"],
            payload["conselho"],
            payload["registro_conselho"],
            payload["uf_conselho"],
            payload["cbo"],
            payload["cbo_descricao"],
            payload["telefone"],
            payload["role"],
            payload["is_active"],
            payload["clinica_id"],
            payload["is_master"],
            payload["is_superuser"],
            payload["cep"],
            payload["logradouro"],
            payload["numero"],
            payload["complemento"],
            payload["bairro"],
            payload["municipio"],
            payload["uf"],
            payload["permissoes_json"],
            uid,
            clinica_id,
        ))

        conn.commit()

        log_edicao(
            modulo="admin_usuarios",
            entidade="usuarios",
            entidade_id=uid,
            descricao="Usuário atualizado.",
            detalhes={
                "clinica_id": clinica_id,
                "nome": payload["nome"],
                "role": payload["role"],
            },
        )

        flash("Usuário atualizado com sucesso.", "success")

    except _integrity_error_class() as e:
        if conn:
            conn.rollback()

        msg = str(e).lower()

        if "cpf_digits" in msg:
            flash("Já existe um usuário com esse CPF.", "error")
        elif "email" in msg:
            flash("Já existe um usuário com esse e-mail.", "error")
        else:
            flash(f"Erro de integridade: {e}", "error")

        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            entidade_id=uid,
            descricao="Erro de integridade ao atualizar usuário.",
            detalhes={"clinica_id": clinica_id},
        )

    except Exception as e:
        if conn:
            conn.rollback()

        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            entidade_id=uid,
            descricao="Erro ao atualizar usuário.",
            detalhes={"clinica_id": clinica_id},
        )

        flash(f"Erro ao atualizar usuário: {e}", "error")

    finally:
        if conn:
            conn.close()

    return _redirect_usuarios()


# =============================================================================
# USUÁRIOS - MUDAR SENHA
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>/senha", methods=["POST"])
@admin_required
@require_permission("admin_usuarios", "editar")
def usuarios_mudar_senha(uid):
    row = load_user(uid)

    if not row:
        flash("Usuário não encontrado.", "error")
        return _redirect_usuarios()

    if not _usuario_pode_manipular_clinica(row.get("clinica_id")):
        abort(403)

    senha = request.form.get("senha") or ""
    senha2 = request.form.get("senha2") or ""

    if not senha or len(senha) < 6:
        flash("Defina uma senha com pelo menos 6 caracteres.", "error")
        return _redirect_usuarios()

    if senha != senha2:
        flash("A confirmação da senha não confere.", "error")
        return _redirect_usuarios()

    conn = None

    try:
        senha_hash = generate_password_hash(
            senha,
            method="pbkdf2:sha256",
            salt_length=16,
        )

        conn = db_conn(False)
        cur = conn.cursor()

        cur.execute("""
            UPDATE usuarios
               SET senha_hash = %s,
                   password_hash = %s,
                   atualizado_em = CURRENT_TIMESTAMP
             WHERE id = %s
               AND COALESCE(clinica_id, 1) = %s;
        """, (senha_hash, senha_hash, uid, _current_clinica_id()))

        conn.commit()

        log_edicao(
            modulo="admin_usuarios",
            entidade="usuarios",
            entidade_id=uid,
            descricao="Senha de usuário atualizada.",
            detalhes={"clinica_id": _current_clinica_id()},
        )

        flash("Senha atualizada com sucesso.", "success")

    except Exception as e:
        if conn:
            conn.rollback()

        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            entidade_id=uid,
            descricao="Erro ao atualizar senha de usuário.",
            detalhes={"clinica_id": _current_clinica_id()},
        )

        flash(f"Erro ao atualizar senha: {e}", "error")

    finally:
        if conn:
            conn.close()

    return _redirect_usuarios()


# =============================================================================
# USUÁRIOS - REMOVER
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>/remover", methods=["POST"])
@admin_required
@require_permission("admin_usuarios", "editar")
def usuarios_remover(uid):
    row = load_user(uid)

    if not row:
        flash("Usuário não encontrado.", "error")
        return _redirect_usuarios()

    if not _usuario_pode_manipular_clinica(row.get("clinica_id")):
        abort(403)

    conn = None

    try:
        conn = db_conn(False)
        cur = conn.cursor()

        cur.execute("""
            DELETE FROM usuarios
             WHERE id = %s
               AND COALESCE(clinica_id, 1) = %s
               AND COALESCE(is_master, FALSE) = FALSE
               AND COALESCE(is_superuser, FALSE) = FALSE;
        """, (uid, _current_clinica_id()))

        conn.commit()

        log_exclusao(
            modulo="admin_usuarios",
            entidade="usuarios",
            entidade_id=uid,
            descricao="Usuário removido.",
            detalhes={
                "clinica_id": _current_clinica_id(),
                "nome": row.get("nome"),
                "role": row.get("role"),
            },
        )

        flash("Usuário removido com sucesso.", "success")

    except Exception as e:
        if conn:
            conn.rollback()

        log_erro(
            "admin_usuarios",
            e,
            entidade="usuarios",
            entidade_id=uid,
            descricao="Erro ao remover usuário.",
            detalhes={"clinica_id": _current_clinica_id()},
        )

        flash(f"Erro ao remover usuário: {e}", "error")

    finally:
        if conn:
            conn.close()

    return _redirect_usuarios()


# =============================================================================
# NÍVEIS - CRIAR
# =============================================================================

@admin_bp.route("/usuarios/niveis/criar", methods=["POST"])
@admin_required
@require_permission("admin_usuarios", "editar")
def niveis_criar():
    nome = request.form.get("nome_nivel", "").strip()
    slug = request.form.get("slug", "").strip()

    if not nome or not slug:
        flash("Informe Nome do nível e Slug.", "error")
        return _redirect_usuarios()

    registrar_log(
        modulo="admin_usuarios",
        acao="criar_nivel_preview",
        entidade="niveis",
        descricao="Criou preview de nível de usuário.",
        detalhes={
            "nome": nome,
            "slug": slug,
            "clinica_id": _current_clinica_id(),
        },
    )

    flash(f"Nível '{nome}' ({slug}) criado (preview).", "success")
    return _redirect_usuarios()