# admin/users.py
from __future__ import annotations

from datetime import datetime
import json

from flask import render_template, request, redirect, url_for, flash, jsonify
from werkzeug.security import generate_password_hash

from . import admin_bp, admin_required
from .helpers import db_conn, only_digits, list_columns


NIVEIS = [
    {
        "slug": "ADMIN",
        "nome": "Administrador",
        "permissoes": [
            "cadastro", "pacientes", "atendimentos", "agenda",
            "export_bpai", "export_apac", "export_ciha",
            "financeiro", "rh"
        ],
    },
    {
        "slug": "RECEPCAO",
        "nome": "Recepção",
        "permissoes": ["cadastro", "pacientes", "atendimentos", "agenda"],
    },
    {
        "slug": "PROFISSIONAL",
        "nome": "Profissional",
        "permissoes": ["pacientes", "atendimentos", "agenda"],
    },
]


# =============================================================================
# HELPERS
# =============================================================================

def _fetchall_as_dicts(cur):
    rows = cur.fetchall() or []
    out = []

    for row in rows:
        if isinstance(row, dict):
            out.append(dict(row))
            continue

        try:
            out.append(dict(row))
            continue
        except Exception:
            pass

        cols = [c[0] for c in cur.description] if cur.description else []
        out.append(dict(zip(cols, row)))

    return out


def _fetchone_as_dict(cur):
    row = cur.fetchone()

    if row is None:
        return None

    if isinstance(row, dict):
        return dict(row)

    try:
        return dict(row)
    except Exception:
        pass

    cols = [c[0] for c in cur.description] if cur.description else []
    return dict(zip(cols, row))


def _normalize_bool(v) -> bool:
    if isinstance(v, bool):
        return v

    return str(v).strip().lower() in {
        "1", "true", "t", "yes", "sim", "ativo"
    }


def _nz(v):
    v = (v or "").strip()
    return v if v else None


def _integrity_error_class():
    try:
        import psycopg
        return psycopg.IntegrityError
    except Exception:
        pass

    try:
        import psycopg2
        return psycopg2.IntegrityError
    except Exception:
        pass

    return Exception


# =============================================================================
# SCHEMA
# =============================================================================

def ensure_users_table():
    conn = db_conn(False)

    try:
        cur = conn.cursor()

        cur.execute("""
            CREATE TABLE IF NOT EXISTS usuarios (
                id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome              TEXT,
                email             TEXT,
                cpf               TEXT,
                cpf_digits        TEXT,
                cns               TEXT,
                nascimento        TEXT,
                sexo              TEXT,
                conselho          TEXT,
                registro_conselho TEXT,
                uf_conselho       TEXT,
                cbo               TEXT,
                cbo_descricao     TEXT,
                telefone          TEXT,
                role              TEXT,
                is_active         BOOLEAN DEFAULT TRUE,
                cep               TEXT,
                logradouro        TEXT,
                numero            TEXT,
                complemento       TEXT,
                bairro            TEXT,
                municipio         TEXT,
                uf                TEXT,
                permissoes_json   TEXT,
                senha_hash        TEXT,
                password_hash     TEXT,
                criado_em         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                atualizado_em     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """)

        cols = list_columns(conn, "usuarios")

        def add_col(name: str, ddl: str):
            nonlocal cols
            if name not in cols:
                cur.execute(f"ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS {ddl};")
                cols = list_columns(conn, "usuarios")

        add_col("nome", "nome TEXT")
        add_col("email", "email TEXT")
        add_col("cpf", "cpf TEXT")
        add_col("cpf_digits", "cpf_digits TEXT")
        add_col("cns", "cns TEXT")
        add_col("nascimento", "nascimento TEXT")
        add_col("sexo", "sexo TEXT")
        add_col("conselho", "conselho TEXT")
        add_col("registro_conselho", "registro_conselho TEXT")
        add_col("uf_conselho", "uf_conselho TEXT")
        add_col("cbo", "cbo TEXT")
        add_col("cbo_descricao", "cbo_descricao TEXT")
        add_col("telefone", "telefone TEXT")
        add_col("role", "role TEXT")
        add_col("is_active", "is_active BOOLEAN DEFAULT TRUE")
        add_col("cep", "cep TEXT")
        add_col("logradouro", "logradouro TEXT")
        add_col("numero", "numero TEXT")
        add_col("complemento", "complemento TEXT")
        add_col("bairro", "bairro TEXT")
        add_col("municipio", "municipio TEXT")
        add_col("uf", "uf TEXT")
        add_col("permissoes_json", "permissoes_json TEXT")
        add_col("senha_hash", "senha_hash TEXT")
        add_col("password_hash", "password_hash TEXT")
        add_col("criado_em", "criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
        add_col("atualizado_em", "atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP")

        cur.execute("""
            UPDATE usuarios
               SET cpf_digits = REGEXP_REPLACE(COALESCE(cpf, ''), '[^0-9]', '', 'g')
             WHERE cpf IS NOT NULL
               AND (cpf_digits IS NULL OR BTRIM(cpf_digits) = '');
        """)

        cur.execute("""
            UPDATE usuarios
               SET criado_em = CURRENT_TIMESTAMP
             WHERE criado_em IS NULL;
        """)

        cur.execute("""
            UPDATE usuarios
               SET atualizado_em = CURRENT_TIMESTAMP
             WHERE atualizado_em IS NULL;
        """)

        cur.execute("""
            UPDATE usuarios
               SET password_hash = senha_hash
             WHERE (password_hash IS NULL OR BTRIM(password_hash) = '')
               AND (senha_hash IS NOT NULL AND BTRIM(senha_hash) <> '');
        """)

        cur.execute("""
            UPDATE usuarios
               SET senha_hash = password_hash
             WHERE (senha_hash IS NULL OR BTRIM(senha_hash) = '')
               AND (password_hash IS NOT NULL AND BTRIM(password_hash) <> '');
        """)

        # Índices únicos parciais
        cur.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_email
                ON usuarios(email)
                WHERE email IS NOT NULL AND BTRIM(email) <> '';
        """)

        cur.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_cpf
                ON usuarios(cpf)
                WHERE cpf IS NOT NULL AND BTRIM(cpf) <> '';
        """)

        cur.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_cpf_digits
                ON usuarios(cpf_digits)
                WHERE cpf_digits IS NOT NULL AND BTRIM(cpf_digits) <> '';
        """)

        conn.commit()

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()


ensure_users_table()


# =============================================================================
# CBO
# =============================================================================

def get_cbo_descricao(codigo: str | None) -> str:
    codigo = only_digits(codigo)[:6]

    if not codigo:
        return ""

    conn = db_conn(True)

    try:
        cur = conn.cursor()

        try:
            cur.execute("""
                SELECT BTRIM(COALESCE(descricao, '')) AS descricao
                  FROM cbo_catalogo
                 WHERE BTRIM(COALESCE(codigo, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            row = _fetchone_as_dict(cur)

            if row and (row.get("descricao") or "").strip():
                return row["descricao"].strip()

        except Exception:
            conn.rollback()

        try:
            cur.execute("""
                SELECT BTRIM(COALESCE(no_ocupacao, '')) AS descricao
                  FROM ocupacoes
                 WHERE BTRIM(COALESCE(co_ocupacao, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            row = _fetchone_as_dict(cur)

            if row:
                return (row.get("descricao") or "").strip()

        except Exception:
            conn.rollback()

        return ""

    finally:
        conn.close()


def cbo_existe_no_catalogo(codigo: str | None) -> bool:
    codigo = only_digits(codigo)[:6]

    if not codigo:
        return False

    conn = db_conn(True)

    try:
        cur = conn.cursor()

        try:
            cur.execute("""
                SELECT 1
                  FROM cbo_catalogo
                 WHERE BTRIM(COALESCE(codigo, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            if cur.fetchone():
                return True

        except Exception:
            conn.rollback()

        try:
            cur.execute("""
                SELECT 1
                  FROM ocupacoes
                 WHERE BTRIM(COALESCE(co_ocupacao, '')) = %s
                 LIMIT 1;
            """, (codigo,))

            return cur.fetchone() is not None

        except Exception:
            conn.rollback()
            return False

    finally:
        conn.close()


def get_cbos_catalogo_local(q: str | None = None, limit: int = 200):
    conn = db_conn(True)

    try:
        cur = conn.cursor()
        q_norm = (q or "").strip()
        q_digits = only_digits(q_norm)

        def montar_items(rows):
            return [
                {
                    "id": (r.get("codigo") or "").strip(),
                    "codigo": (r.get("codigo") or "").strip(),
                    "descricao": (r.get("descricao") or "").strip(),
                    "label": f"{(r.get('codigo') or '').strip()} - {(r.get('descricao') or '').strip()}".strip(" -"),
                }
                for r in rows
                if (r.get("codigo") or "").strip()
            ]

        try:
            sql = """
                SELECT
                    BTRIM(COALESCE(codigo, '')) AS codigo,
                    BTRIM(COALESCE(descricao, '')) AS descricao
                  FROM cbo_catalogo
                 WHERE BTRIM(COALESCE(codigo, '')) <> ''
            """
            params = []

            if q_norm:
                sql += """
                   AND (
                        CAST(codigo AS TEXT) ILIKE %s
                        OR COALESCE(descricao, '') ILIKE %s
                   )
                """
                params.extend([f"%{q_digits or q_norm}%", f"%{q_norm}%"])

            sql += """
                 ORDER BY codigo ASC
                 LIMIT %s;
            """
            params.append(int(limit))

            cur.execute(sql, params)
            items = montar_items(_fetchall_as_dicts(cur))

            if items:
                return items

        except Exception:
            conn.rollback()

        try:
            sql = """
                SELECT
                    BTRIM(COALESCE(co_ocupacao, '')) AS codigo,
                    BTRIM(COALESCE(no_ocupacao, '')) AS descricao
                  FROM ocupacoes
                 WHERE BTRIM(COALESCE(co_ocupacao, '')) <> ''
            """
            params = []

            if q_norm:
                sql += """
                   AND (
                        CAST(co_ocupacao AS TEXT) ILIKE %s
                        OR COALESCE(no_ocupacao, '') ILIKE %s
                   )
                """
                params.extend([f"%{q_digits or q_norm}%", f"%{q_norm}%"])

            sql += """
                 ORDER BY codigo ASC
                 LIMIT %s;
            """
            params.append(int(limit))

            cur.execute(sql, params)
            return montar_items(_fetchall_as_dicts(cur))

        except Exception:
            conn.rollback()
            return []

    finally:
        conn.close()


# =============================================================================
# USER HELPERS
# =============================================================================

def load_user(uid: int):
    conn = db_conn(True)

    try:
        # limpa qualquer transação abortada anterior
        try:
            conn.rollback()
        except Exception:
            pass

        cur = conn.cursor()

        cur.execute("""
            SELECT *
              FROM usuarios
             WHERE id = %s
             LIMIT 1;
        """, (uid,))

        return _fetchone_as_dict(cur)

    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        raise

    finally:
        try:
            conn.close()
        except Exception:
            pass

# =============================================================================
# API CBO
# =============================================================================

@admin_bp.route("/api/cbos-catalogo/buscar")
@admin_required
def cbos_catalogo_buscar():
    q = (request.args.get("q") or "").strip()

    if len(q) < 2:
        return jsonify({"ok": True, "q": q, "items": []})

    items = get_cbos_catalogo_local(q=q, limit=20)
    return jsonify({"ok": True, "q": q, "items": items})


# =============================================================================
# DASHBOARD
# =============================================================================

@admin_bp.route("/")
@admin_required
def admin_home():
    total_usuarios = 0
    usuarios_ativos = 0

    conn = None

    try:
        ensure_users_table()

        conn = db_conn(True)
        cur = conn.cursor()

        cur.execute("""
            SELECT
                COUNT(1) AS total_usuarios,
                SUM(CASE WHEN COALESCE(is_active, FALSE) = TRUE THEN 1 ELSE 0 END) AS usuarios_ativos
              FROM usuarios;
        """)

        row = _fetchone_as_dict(cur) or {}

        total_usuarios = int(row.get("total_usuarios") or 0)
        usuarios_ativos = int(row.get("usuarios_ativos") or 0)

    except Exception:
        if conn:
            conn.rollback()

    finally:
        if conn:
            conn.close()

    ctx = {
        "total_usuarios": total_usuarios,
        "usuarios_ativos": usuarios_ativos,
        "modulos_habilitados": 3,
        "ultimo_backup": datetime.now().strftime("%d/%m/%Y %H:%M"),
    }

    return render_template("admin.html", **ctx)


# =============================================================================
# USUÁRIOS - LISTAR
# =============================================================================

@admin_bp.route("/usuarios")
@admin_required
def usuarios_listar():
    usuarios = []
    conn = None

    try:
        ensure_users_table()

        conn = db_conn(True)
        cur = conn.cursor()

        mapa_cbo = {}

        try:
            cur.execute("""
                SELECT
                    BTRIM(COALESCE(codigo, '')) AS codigo,
                    BTRIM(COALESCE(descricao, '')) AS descricao
                  FROM cbo_catalogo
                 WHERE BTRIM(COALESCE(codigo, '')) <> '';
            """)

            for r in _fetchall_as_dicts(cur):
                mapa_cbo[(r.get("codigo") or "").strip()] = (r.get("descricao") or "").strip()

        except Exception:
            conn.rollback()
            mapa_cbo = {}

        cur.execute("""
            SELECT
                id,
                nome,
                cpf,
                cpf_digits,
                email,
                role,
                is_active,
                criado_em,
                cbo,
                cbo_descricao
              FROM usuarios
             ORDER BY id DESC;
        """)

        rows = _fetchall_as_dicts(cur)

        for r in rows:
            cbo_codigo = (r.get("cbo") or "").strip()
            cbo_descricao = (r.get("cbo_descricao") or "").strip()

            if not cbo_descricao:
                cbo_descricao = mapa_cbo.get(cbo_codigo, "")

            usuarios.append({
                "id": r.get("id"),
                "nome": r.get("nome"),
                "cpf": r.get("cpf"),
                "cpf_digits": r.get("cpf_digits"),
                "email": r.get("email"),
                "role": r.get("role"),
                "is_active": _normalize_bool(r.get("is_active")),
                "criado_em": r.get("criado_em"),
                "cbo": cbo_codigo,
                "cbo_descricao": cbo_descricao,
                "cbo_label": f"{cbo_codigo} — {cbo_descricao}" if cbo_codigo and cbo_descricao else (cbo_codigo or "—"),
            })

    except Exception as e:
        if conn:
            conn.rollback()
        flash(f"Falha ao carregar usuários: {e}", "error")

    finally:
        if conn:
            conn.close()

    return render_template(
        "admin-usuarios.html",
        usuarios=usuarios,
        niveis=NIVEIS,
        cbos_catalogo=get_cbos_catalogo_local(limit=200),
    )


# =============================================================================
# USUÁRIOS - CRIAR
# =============================================================================

@admin_bp.route("/usuarios/novo", methods=["GET", "POST"])
@admin_required
def usuarios_criar():
    if request.method != "POST":
        return redirect(url_for("admin.usuarios_listar"))

    conn = None

    try:
        nome = (request.form.get("nome") or "").strip()
        cpf = (request.form.get("cpf") or "").strip()
        role = (request.form.get("role") or "").strip() or "RECEPCAO"
        is_active_raw = request.form.get("is_active") or "1"

        if not nome or not cpf or not role:
            flash("Preencha ao menos Nome, CPF e Nível.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        cpf_digits = only_digits(cpf)

        if len(cpf_digits) != 11:
            flash("CPF inválido. Informe 11 dígitos.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        senha = request.form.get("senha") or ""
        senha2 = request.form.get("senha2") or ""

        if not senha or len(senha) < 6:
            flash("Defina uma senha com pelo menos 6 caracteres.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        if senha != senha2:
            flash("A confirmação da senha não confere.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        senha_hash = generate_password_hash(
            senha,
            method="pbkdf2:sha256",
            salt_length=16,
        )

        email = _nz(request.form.get("email"))
        cns = _nz(request.form.get("cns"))
        nascimento = _nz(request.form.get("nascimento"))
        sexo = _nz(request.form.get("sexo"))

        conselho = _nz(request.form.get("conselho"))
        registro_conselho = _nz(request.form.get("registro_conselho"))
        uf_conselho = _nz(request.form.get("uf_conselho"))

        cbo = _nz(only_digits(request.form.get("cbo"))[:6])

        if cbo and not cbo_existe_no_catalogo(cbo):
            flash("O CBO informado não existe no catálogo local.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        cbo_descricao = get_cbo_descricao(cbo) if cbo else None

        telefone = _nz(request.form.get("telefone"))
        cep = _nz(request.form.get("cep"))
        logradouro = _nz(request.form.get("logradouro"))
        numero = _nz(request.form.get("numero"))
        complemento = _nz(request.form.get("complemento"))
        bairro = _nz(request.form.get("bairro"))
        municipio = _nz(request.form.get("municipio"))
        uf = _nz(request.form.get("uf"))

        permissoes = []

        for k in request.form.keys():
            if k.startswith("perm_") and request.form.get(k) == "1":
                permissoes.append(k.replace("perm_", "", 1))

        permissoes_json = json.dumps(permissoes, ensure_ascii=False) if permissoes else None

        ensure_users_table()

        conn = db_conn(False)
        cur = conn.cursor()

        is_active = str(is_active_raw) == "1"

        cur.execute("""
            INSERT INTO usuarios (
                nome,
                email,
                cpf,
                cpf_digits,
                cns,
                nascimento,
                sexo,
                conselho,
                registro_conselho,
                uf_conselho,
                cbo,
                cbo_descricao,
                telefone,
                role,
                is_active,
                cep,
                logradouro,
                numero,
                complemento,
                bairro,
                municipio,
                uf,
                permissoes_json,
                senha_hash,
                password_hash,
                criado_em,
                atualizado_em
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            )
            RETURNING id;
        """, (
            nome,
            email,
            cpf,
            cpf_digits,
            cns,
            nascimento,
            sexo,
            conselho,
            registro_conselho,
            uf_conselho,
            cbo,
            cbo_descricao,
            telefone,
            role,
            is_active,
            cep,
            logradouro,
            numero,
            complemento,
            bairro,
            municipio,
            uf,
            permissoes_json,
            senha_hash,
            senha_hash,
        ))

        cur.fetchone()
        conn.commit()

        flash("Usuário criado com sucesso.", "success")
        return redirect(url_for("admin.usuarios_listar"))

    except _integrity_error_class() as e:
        if conn:
            conn.rollback()

        msg = str(e).lower()

        if "cpf_digits" in msg or "idx_usuarios_cpf_digits" in msg:
            flash("Já existe um usuário com esse CPF.", "error")
        elif "idx_usuarios_cpf" in msg or "usuarios_cpf_key" in msg:
            flash("Já existe um usuário com esse CPF.", "error")
        elif "idx_usuarios_email" in msg or "usuarios_email_key" in msg:
            flash("Já existe um usuário com esse e-mail.", "error")
        else:
            flash(f"Erro de integridade ao salvar o usuário: {e}", "error")

        return redirect(url_for("admin.usuarios_listar"))

    except Exception as e:
        if conn:
            conn.rollback()

        flash(f"Erro ao criar usuário: {e}", "error")
        return redirect(url_for("admin.usuarios_listar"))

    finally:
        if conn:
            conn.close()


# =============================================================================
# USUÁRIOS - JSON
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>.json")
@admin_required
def usuarios_json(uid):
    row = load_user(uid)

    if not row:
        return jsonify({"error": "Usuário não encontrado"}), 404

    data = dict(row)

    # Nunca enviar hashes para o front
    data.pop("senha_hash", None)
    data.pop("password_hash", None)

    # Converte datas/timestamps para texto
    for campo in ("criado_em", "atualizado_em", "nascimento", "last_login_at", "created_at"):
        if campo in data and data[campo] is not None:
            try:
                data[campo] = data[campo].isoformat()
            except Exception:
                data[campo] = str(data[campo])

    # Normaliza booleano
    data["is_active"] = _normalize_bool(data.get("is_active"))

    cbo_codigo = (data.get("cbo") or "").strip()
    cbo_descricao = (data.get("cbo_descricao") or "").strip()

    if cbo_codigo and not cbo_descricao:
        cbo_descricao = get_cbo_descricao(cbo_codigo)

    data["cbo_descricao"] = cbo_descricao
    data["cbo_label"] = (
        f"{cbo_codigo} — {cbo_descricao}"
        if cbo_codigo and cbo_descricao
        else (cbo_codigo or "")
    )

    return jsonify(data)

# =============================================================================
# USUÁRIOS - EDITAR
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>/editar", methods=["POST"])
@admin_required
def usuarios_editar(uid):
    conn = None

    try:
        # 🔥 carrega o usuário com proteção contra transação abortada
        row = load_user(uid)

        if not row:
            flash("Usuário não encontrado.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        nome = (request.form.get("nome") or "").strip()
        cpf = (request.form.get("cpf") or "").strip()
        role = (request.form.get("role") or "").strip() or row.get("role")
        is_active_raw = request.form.get("is_active") or "1"

        if not nome or not cpf or not role:
            flash("Preencha Nome, CPF e Nível.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        cpf_digits = only_digits(cpf)

        if len(cpf_digits) != 11:
            flash("CPF inválido. Informe 11 dígitos.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        email = _nz(request.form.get("email"))
        cns = _nz(request.form.get("cns"))
        nascimento = _nz(request.form.get("nascimento"))
        sexo = _nz(request.form.get("sexo"))

        conselho = _nz(request.form.get("conselho"))
        registro_conselho = _nz(request.form.get("registro_conselho"))
        uf_conselho = _nz(request.form.get("uf_conselho"))

        cbo = _nz(only_digits(request.form.get("cbo"))[:6])

        if cbo and not cbo_existe_no_catalogo(cbo):
            flash("O CBO informado não existe no catálogo local.", "error")
            return redirect(url_for("admin.usuarios_listar"))

        cbo_descricao = get_cbo_descricao(cbo) if cbo else None

        telefone = _nz(request.form.get("telefone"))
        cep = _nz(request.form.get("cep"))
        logradouro = _nz(request.form.get("logradouro"))
        numero = _nz(request.form.get("numero"))
        complemento = _nz(request.form.get("complemento"))
        bairro = _nz(request.form.get("bairro"))
        municipio = _nz(request.form.get("municipio"))
        uf = _nz(request.form.get("uf"))

        permissoes = []

        for k in request.form.keys():
            if k.startswith("perm_") and request.form.get(k) == "1":
                permissoes.append(k.replace("perm_", "", 1))

        permissoes_json = json.dumps(permissoes, ensure_ascii=False)
        is_active = str(is_active_raw) == "1"

        conn = db_conn(False)

        # 🔥 garante que a conexão não esteja abortada
        try:
            conn.rollback()
        except Exception:
            pass

        cur = conn.cursor()

        cur.execute("""
            UPDATE usuarios SET
                nome = %s,
                email = %s,
                cpf = %s,
                cpf_digits = %s,
                cns = %s,
                nascimento = %s,
                sexo = %s,
                conselho = %s,
                registro_conselho = %s,
                uf_conselho = %s,
                cbo = %s,
                cbo_descricao = %s,
                telefone = %s,
                role = %s,
                is_active = %s,
                cep = %s,
                logradouro = %s,
                numero = %s,
                complemento = %s,
                bairro = %s,
                municipio = %s,
                uf = %s,
                permissoes_json = %s,
                atualizado_em = CURRENT_TIMESTAMP
            WHERE id = %s;
        """, (
            nome,
            email,
            cpf,
            cpf_digits,
            cns,
            nascimento,
            sexo,
            conselho,
            registro_conselho,
            uf_conselho,
            cbo,
            cbo_descricao,
            telefone,
            role,
            is_active,
            cep,
            logradouro,
            numero,
            complemento,
            bairro,
            municipio,
            uf,
            permissoes_json,
            uid,
        ))

        conn.commit()
        flash("Usuário atualizado com sucesso.", "success")

    except _integrity_error_class() as e:
        if conn:
            conn.rollback()

        msg = str(e).lower()

        if "cpf_digits" in msg:
            flash("Já existe um usuário com esse CPF.", "error")
        elif "email" in msg:
            flash("Já existe um usuário com esse e-mail.", "error")
        else:
            flash(f"Erro de integridade: {e}", "error")

    except Exception as e:
        if conn:
            conn.rollback()

        flash(f"Erro ao atualizar usuário: {e}", "error")

    finally:
        if conn:
            conn.close()

    return redirect(url_for("admin.usuarios_listar"))

# =============================================================================
# USUÁRIOS - MUDAR SENHA
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>/senha", methods=["POST"])
@admin_required
def usuarios_mudar_senha(uid):
    row = load_user(uid)

    if not row:
        flash("Usuário não encontrado.", "error")
        return redirect(url_for("admin.usuarios_listar"))

    senha = request.form.get("senha") or ""
    senha2 = request.form.get("senha2") or ""

    if not senha or len(senha) < 6:
        flash("Defina uma senha com pelo menos 6 caracteres.", "error")
        return redirect(url_for("admin.usuarios_listar"))

    if senha != senha2:
        flash("A confirmação da senha não confere.", "error")
        return redirect(url_for("admin.usuarios_listar"))

    conn = None

    try:
        senha_hash = generate_password_hash(
            senha,
            method="pbkdf2:sha256",
            salt_length=16,
        )

        conn = db_conn(False)
        cur = conn.cursor()

        cur.execute("""
            UPDATE usuarios
               SET senha_hash = %s,
                   password_hash = %s,
                   atualizado_em = CURRENT_TIMESTAMP
             WHERE id = %s;
        """, (senha_hash, senha_hash, uid))

        conn.commit()

        flash("Senha atualizada com sucesso.", "success")

    except Exception as e:
        if conn:
            conn.rollback()

        flash(f"Erro ao atualizar senha: {e}", "error")

    finally:
        if conn:
            conn.close()

    return redirect(url_for("admin.usuarios_listar"))


# =============================================================================
# USUÁRIOS - REMOVER
# =============================================================================

@admin_bp.route("/usuarios/<int:uid>/remover", methods=["POST"])
@admin_required
def usuarios_remover(uid):
    row = load_user(uid)

    if not row:
        flash("Usuário não encontrado.", "error")
        return redirect(url_for("admin.usuarios_listar"))

    conn = None

    try:
        conn = db_conn(False)
        cur = conn.cursor()

        cur.execute("DELETE FROM usuarios WHERE id = %s;", (uid,))
        conn.commit()

        flash("Usuário removido com sucesso.", "success")

    except Exception as e:
        if conn:
            conn.rollback()

        flash(f"Erro ao remover usuário: {e}", "error")

    finally:
        if conn:
            conn.close()

    return redirect(url_for("admin.usuarios_listar"))


# =============================================================================
# NÍVEIS - CRIAR
# =============================================================================

@admin_bp.route("/usuarios/niveis/criar", methods=["POST"])
@admin_required
def niveis_criar():
    nome = request.form.get("nome_nivel", "").strip()
    slug = request.form.get("slug", "").strip()

    if not nome or not slug:
        flash("Informe Nome do nível e Slug.", "error")
        return redirect(url_for("admin.usuarios_listar"))

    flash(f"Nível '{nome}' ({slug}) criado (preview).", "success")
    return redirect(url_for("admin.usuarios_listar"))